package com.guinea.account.entity;
// Generated 2011-1-1 21:16:04 by Hibernate Tools 3.4.0.Beta1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.guinea.core.orm.BaseEntity;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements BaseEntity {


     /**
	 * 
	 */
	private static final long serialVersionUID = 8117145333699070124L;
	private Long id;
    private Integer serial;
	private Long parentId;
    private String name;
    private String title;
     private String menuType;
     private String url;
     private String status;
     private Long creator;
     private Date created;
     private Long modificator;
     private Date modified;
     private Set roles = new HashSet(0);

    public Menu() {
    }

	
    public Menu(String name, String menuType, String status, Long creator, Date created) {
        this.name = name;
        this.menuType = menuType;
        this.status = status;
        this.creator = creator;
        this.created = created;
    }
    public Menu(Long parentId, String name, String menuType, String url, String status, Long creator, Date created, Long modificator, Date modified, Set roles) {
       this.parentId = parentId;
       this.name = name;
       this.menuType = menuType;
       this.url = url;
       this.status = status;
       this.creator = creator;
       this.created = created;
       this.modificator = modificator;
       this.modified = modified;
       this.roles = roles;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSerial() {
		return serial;
	}


	public void setSerial(Integer serial) {
		this.serial = serial;
	}


	public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getTitle() {
		return title;
	}


	public void setTitle(String title) {
		this.title = title;
	}


	public String getMenuType() {
		return menuType;
	}


	public void setMenuType(String menuType) {
		this.menuType = menuType;
	}

	public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Long getCreator() {
        return this.creator;
    }
    
    public void setCreator(Long creator) {
        this.creator = creator;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Long getModificator() {
        return this.modificator;
    }
    
    public void setModificator(Long modificator) {
        this.modificator = modificator;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public Set getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set roles) {
        this.roles = roles;
    }


	public Long getParentId() {
		return parentId;
	}


	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

}


