package com.guinea.account.entity;
// Generated 2011-1-1 21:16:04 by Hibernate Tools 3.4.0.Beta1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.guinea.core.orm.BaseEntity;

/**
 * Role generated by hbm2java
 */
public class Role  implements BaseEntity {


     /**
	 * 
	 */
	private static final long serialVersionUID = -8716257639592654416L;
	private Long id;
     private String roleType;
     private String name;
     private String status;
     private Long creator;
     private Date created;
     private Long modificator;
     private Date modified;
     private Set resources = new HashSet(0);
     private Set users = new HashSet(0);
     private Set menus = new HashSet(0);

    public Role() {
    }

	
    public Role(String roleType, String name, String status, Long creator, Date created) {
        this.roleType = roleType;
        this.name = name;
        this.status = status;
        this.creator = creator;
        this.created = created;
    }
    public Role(String roleType, String name, String status, Long creator, Date created, Long modificator, Date modified, Set resources, Set users, Set menus) {
       this.roleType = roleType;
       this.name = name;
       this.status = status;
       this.creator = creator;
       this.created = created;
       this.modificator = modificator;
       this.modified = modified;
       this.resources = resources;
       this.users = users;
       this.menus = menus;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

	public String getRoleType() {
		return roleType;
	}

	public void setRoleType(String roleType) {
		this.roleType = roleType;
	}


	public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Long getCreator() {
        return this.creator;
    }
    
    public void setCreator(Long creator) {
        this.creator = creator;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Long getModificator() {
        return this.modificator;
    }
    
    public void setModificator(Long modificator) {
        this.modificator = modificator;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public Set getResources() {
        return this.resources;
    }
    
    public void setResources(Set resources) {
        this.resources = resources;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
    public Set getMenus() {
        return this.menus;
    }
    
    public void setMenus(Set menus) {
        this.menus = menus;
    }




}


