package com.guinea.account.entity;
// Generated 2010-12-20 19:06:36 by Hibernate Tools 3.4.0.Beta1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SvwUsermsg generated by hbm2java
 */
public class SvwUsermsg  implements java.io.Serializable {


     private BigDecimal userid;
     private String loginname;
     private String passwd;
     private char workflg;
     private String datetime;
     private char onlnflg;
     private char userflag;
     private BigDecimal empid;
     private BigDecimal grpid;
     private BigDecimal loginid;
     private BigDecimal funcid;
     private String rmk;
     private BigDecimal crtuser;
     private String crttime;
     private BigDecimal updtuser;
     private String updttime;
     private String vpdaStatus;
     private String vpdaFrcout;
     private String vpdaReset;
     private String vpdaMachid;
     private String vpdaPhone;
     private String vpdaStdate;
     private String vpdaFbdate;
     private String vpdaUpdate;
     private String portalid;
     private Set svwUserrolerels = new HashSet(0);

    public SvwUsermsg() {
    }

	
    public SvwUsermsg(BigDecimal userid, String loginname, String passwd, char workflg, String datetime, char onlnflg, char userflag, BigDecimal empid, BigDecimal grpid, BigDecimal loginid, BigDecimal crtuser, String crttime) {
        this.userid = userid;
        this.loginname = loginname;
        this.passwd = passwd;
        this.workflg = workflg;
        this.datetime = datetime;
        this.onlnflg = onlnflg;
        this.userflag = userflag;
        this.empid = empid;
        this.grpid = grpid;
        this.loginid = loginid;
        this.crtuser = crtuser;
        this.crttime = crttime;
    }
    public SvwUsermsg(BigDecimal userid, String loginname, String passwd, char workflg, String datetime, char onlnflg, char userflag, BigDecimal empid, BigDecimal grpid, BigDecimal loginid, BigDecimal funcid, String rmk, BigDecimal crtuser, String crttime, BigDecimal updtuser, String updttime, String vpdaStatus, String vpdaFrcout, String vpdaReset, String vpdaMachid, String vpdaPhone, String vpdaStdate, String vpdaFbdate, String vpdaUpdate, String portalid, Set svwUserrolerels) {
       this.userid = userid;
       this.loginname = loginname;
       this.passwd = passwd;
       this.workflg = workflg;
       this.datetime = datetime;
       this.onlnflg = onlnflg;
       this.userflag = userflag;
       this.empid = empid;
       this.grpid = grpid;
       this.loginid = loginid;
       this.funcid = funcid;
       this.rmk = rmk;
       this.crtuser = crtuser;
       this.crttime = crttime;
       this.updtuser = updtuser;
       this.updttime = updttime;
       this.vpdaStatus = vpdaStatus;
       this.vpdaFrcout = vpdaFrcout;
       this.vpdaReset = vpdaReset;
       this.vpdaMachid = vpdaMachid;
       this.vpdaPhone = vpdaPhone;
       this.vpdaStdate = vpdaStdate;
       this.vpdaFbdate = vpdaFbdate;
       this.vpdaUpdate = vpdaUpdate;
       this.portalid = portalid;
       this.svwUserrolerels = svwUserrolerels;
    }
   
    public BigDecimal getUserid() {
        return this.userid;
    }
    
    public void setUserid(BigDecimal userid) {
        this.userid = userid;
    }
    public String getLoginname() {
        return this.loginname;
    }
    
    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
    public char getWorkflg() {
        return this.workflg;
    }
    
    public void setWorkflg(char workflg) {
        this.workflg = workflg;
    }
    public String getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(String datetime) {
        this.datetime = datetime;
    }
    public char getOnlnflg() {
        return this.onlnflg;
    }
    
    public void setOnlnflg(char onlnflg) {
        this.onlnflg = onlnflg;
    }
    public char getUserflag() {
        return this.userflag;
    }
    
    public void setUserflag(char userflag) {
        this.userflag = userflag;
    }
    public BigDecimal getEmpid() {
        return this.empid;
    }
    
    public void setEmpid(BigDecimal empid) {
        this.empid = empid;
    }
    public BigDecimal getGrpid() {
        return this.grpid;
    }
    
    public void setGrpid(BigDecimal grpid) {
        this.grpid = grpid;
    }
    public BigDecimal getLoginid() {
        return this.loginid;
    }
    
    public void setLoginid(BigDecimal loginid) {
        this.loginid = loginid;
    }
    public BigDecimal getFuncid() {
        return this.funcid;
    }
    
    public void setFuncid(BigDecimal funcid) {
        this.funcid = funcid;
    }
    public String getRmk() {
        return this.rmk;
    }
    
    public void setRmk(String rmk) {
        this.rmk = rmk;
    }
    public BigDecimal getCrtuser() {
        return this.crtuser;
    }
    
    public void setCrtuser(BigDecimal crtuser) {
        this.crtuser = crtuser;
    }
    public String getCrttime() {
        return this.crttime;
    }
    
    public void setCrttime(String crttime) {
        this.crttime = crttime;
    }
    public BigDecimal getUpdtuser() {
        return this.updtuser;
    }
    
    public void setUpdtuser(BigDecimal updtuser) {
        this.updtuser = updtuser;
    }
    public String getUpdttime() {
        return this.updttime;
    }
    
    public void setUpdttime(String updttime) {
        this.updttime = updttime;
    }
    public String getVpdaStatus() {
        return this.vpdaStatus;
    }
    
    public void setVpdaStatus(String vpdaStatus) {
        this.vpdaStatus = vpdaStatus;
    }
    public String getVpdaFrcout() {
        return this.vpdaFrcout;
    }
    
    public void setVpdaFrcout(String vpdaFrcout) {
        this.vpdaFrcout = vpdaFrcout;
    }
    public String getVpdaReset() {
        return this.vpdaReset;
    }
    
    public void setVpdaReset(String vpdaReset) {
        this.vpdaReset = vpdaReset;
    }
    public String getVpdaMachid() {
        return this.vpdaMachid;
    }
    
    public void setVpdaMachid(String vpdaMachid) {
        this.vpdaMachid = vpdaMachid;
    }
    public String getVpdaPhone() {
        return this.vpdaPhone;
    }
    
    public void setVpdaPhone(String vpdaPhone) {
        this.vpdaPhone = vpdaPhone;
    }
    public String getVpdaStdate() {
        return this.vpdaStdate;
    }
    
    public void setVpdaStdate(String vpdaStdate) {
        this.vpdaStdate = vpdaStdate;
    }
    public String getVpdaFbdate() {
        return this.vpdaFbdate;
    }
    
    public void setVpdaFbdate(String vpdaFbdate) {
        this.vpdaFbdate = vpdaFbdate;
    }
    public String getVpdaUpdate() {
        return this.vpdaUpdate;
    }
    
    public void setVpdaUpdate(String vpdaUpdate) {
        this.vpdaUpdate = vpdaUpdate;
    }
    public String getPortalid() {
        return this.portalid;
    }
    
    public void setPortalid(String portalid) {
        this.portalid = portalid;
    }
    public Set getSvwUserrolerels() {
        return this.svwUserrolerels;
    }
    
    public void setSvwUserrolerels(Set svwUserrolerels) {
        this.svwUserrolerels = svwUserrolerels;
    }




}


