package com.guinea.account.entity;
// Generated 2010-12-20 19:06:36 by Hibernate Tools 3.4.0.Beta1


import java.math.BigDecimal;

/**
 * SvwUserrolerel generated by hbm2java
 */
public class SvwUserrolerel  implements java.io.Serializable {


     private SvwUserrolerelId id;
     private SvwUsermsg svwUsermsg;
     private SvwRolemsg svwRolemsg;
     private BigDecimal crtuser;
     private String crttime;
     private BigDecimal updtuser;
     private String updttime;

    public SvwUserrolerel() {
    }

	
    public SvwUserrolerel(SvwUserrolerelId id, SvwUsermsg svwUsermsg, SvwRolemsg svwRolemsg, BigDecimal crtuser, String crttime) {
        this.id = id;
        this.svwUsermsg = svwUsermsg;
        this.svwRolemsg = svwRolemsg;
        this.crtuser = crtuser;
        this.crttime = crttime;
    }
    public SvwUserrolerel(SvwUserrolerelId id, SvwUsermsg svwUsermsg, SvwRolemsg svwRolemsg, BigDecimal crtuser, String crttime, BigDecimal updtuser, String updttime) {
       this.id = id;
       this.svwUsermsg = svwUsermsg;
       this.svwRolemsg = svwRolemsg;
       this.crtuser = crtuser;
       this.crttime = crttime;
       this.updtuser = updtuser;
       this.updttime = updttime;
    }
   
    public SvwUserrolerelId getId() {
        return this.id;
    }
    
    public void setId(SvwUserrolerelId id) {
        this.id = id;
    }
    public SvwUsermsg getSvwUsermsg() {
        return this.svwUsermsg;
    }
    
    public void setSvwUsermsg(SvwUsermsg svwUsermsg) {
        this.svwUsermsg = svwUsermsg;
    }
    public SvwRolemsg getSvwRolemsg() {
        return this.svwRolemsg;
    }
    
    public void setSvwRolemsg(SvwRolemsg svwRolemsg) {
        this.svwRolemsg = svwRolemsg;
    }
    public BigDecimal getCrtuser() {
        return this.crtuser;
    }
    
    public void setCrtuser(BigDecimal crtuser) {
        this.crtuser = crtuser;
    }
    public String getCrttime() {
        return this.crttime;
    }
    
    public void setCrttime(String crttime) {
        this.crttime = crttime;
    }
    public BigDecimal getUpdtuser() {
        return this.updtuser;
    }
    
    public void setUpdtuser(BigDecimal updtuser) {
        this.updtuser = updtuser;
    }
    public String getUpdttime() {
        return this.updttime;
    }
    
    public void setUpdttime(String updttime) {
        this.updttime = updttime;
    }




}


