package com.guinea.account.entity;
// Generated 2011-1-1 21:16:04 by Hibernate Tools 3.4.0.Beta1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.guinea.core.orm.BaseEntity;

/**
 * Resource generated by hbm2java
 */
public class Resource  implements BaseEntity {


     /**
	 * 
	 */
	private static final long serialVersionUID = -3715652299367874783L;
	private Long id;
     private String name;
     private String resourceType;
     private String resourceString;
     private String status;
     private Long creator;
     private Date created;
     private Long modificator;
     private Date modified;
     private Set roles = new HashSet(0);

    public Resource() {
    }

	
    public Resource(String name, String resourceType, String resourceString, String status, Long creator, Date created) {
        this.name = name;
        this.resourceType = resourceType;
        this.resourceString = resourceString;
        this.status = status;
        this.creator = creator;
        this.created = created;
    }
    public Resource(String name, String resourceType, String resourceString, String status, Long creator, Date created, Long modificator, Date modified, Set roles) {
       this.name = name;
       this.resourceType = resourceType;
       this.resourceString = resourceString;
       this.status = status;
       this.creator = creator;
       this.created = created;
       this.modificator = modificator;
       this.modified = modified;
       this.roles = roles;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getResourceType() {
        return this.resourceType;
    }
    
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }
    public String getResourceString() {
        return this.resourceString;
    }
    
    public void setResourceString(String resourceString) {
        this.resourceString = resourceString;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Long getCreator() {
        return this.creator;
    }
    
    public void setCreator(Long creator) {
        this.creator = creator;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Long getModificator() {
        return this.modificator;
    }
    
    public void setModificator(Long modificator) {
        this.modificator = modificator;
    }
    public Date getModified() {
        return this.modified;
    }
    
    public void setModified(Date modified) {
        this.modified = modified;
    }
    public Set getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set roles) {
        this.roles = roles;
    }




}


